# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 278cbb108e1c8b52534b51798361bc2704f20a995a2e4e510ef75ddba2a25bc2d53f3bd0ea85d8e9a616db43731c8fc5205286ced4ec3fb60fdda896468b4f58

test:
  secret_key_base: 31267dc61bdf58241f073d0a80d27951e613fe50f5e725ad9d5a39ce044b8a9b6870a556958b957a156a5bb70844c3949faf6757f177913160dc145529e8569e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
